<?php

return array(
    "auto_action" => __("Scan action", 'us-barcode-scanner'),
    "auto_action_desc" => __("To do after barcode scan:", 'us-barcode-scanner'),
    "rb_none" => __("None", 'us-barcode-scanner'),
    "rb_increase" => __("Increase stock quantity (+1)", 'us-barcode-scanner'),
    "rb_decrease" => __("Decrease stock quantity (-1)", 'us-barcode-scanner'),
    "rb_action_increase" => __("Increase stock quantity", 'us-barcode-scanner'),
    "rb_action_decrease" => __("Decrease stock quantity", 'us-barcode-scanner'),
    "link_more_settings" => __("Settings", 'us-barcode-scanner'),
    "link_system_information" => __("System information", 'us-barcode-scanner'),
    "link_exit" => __("Exit", 'us-barcode-scanner'),
    "btn_switch_store" => __("Switch store", 'us-barcode-scanner'),
    "switch_store_desc" => __("Click on a shop you would like to switch to", 'us-barcode-scanner'),
    "btn_logout" => __("Log out", 'us-barcode-scanner'),
    "btn_logout_desc" => __("Once log out you will need to login with a new One Time Password", 'us-barcode-scanner'),
    "link_contact_us" => __("Contact us", 'us-barcode-scanner'),
    "link_privacy_policy" => __("Privacy policy", 'us-barcode-scanner'),
    "link_terms" => __("Terms of use", 'us-barcode-scanner'),
    "logged_in_as" => __("Logged in as:", 'us-barcode-scanner'),
    "btn_login_to_new_store" => __("Login to a new store", 'us-barcode-scanner'),
    "btn_logout_confirmation" => __("Confirmation", 'us-barcode-scanner'),
    "btn_logout_confirmation_desc" => __("Are you sure that you want to log out?", 'us-barcode-scanner'),
    "btn_app_close" => __("Close", 'us-barcode-scanner'),
    "btn_app_restart" => __("Restart", 'us-barcode-scanner'),
    "btn_app_logout" => __("Log out", 'us-barcode-scanner'),
    "btn_app_login" => __("Login", 'us-barcode-scanner'),
    "btn_app_exit" => __("Exit", 'us-barcode-scanner'),
    "alert_default_title" => __("Info", 'us-barcode-scanner'),

    "nav_products" => __("Products", 'us-barcode-scanner'),
    "nav_orders" => __("Orders", 'us-barcode-scanner'),
    "nav_edit" => __("Edit", 'us-barcode-scanner'),
    "nav_qty" => __("Qty", 'us-barcode-scanner'),
    "nav_qty_p" => __("Qty +1", 'us-barcode-scanner'),
    "nav_qty_m" => __("Qty -1", 'us-barcode-scanner'),
    "nav_new" => __("New", 'us-barcode-scanner'),
    "nav_save" => __("Save", 'us-barcode-scanner'),
    "nav_list" => __("List", 'us-barcode-scanner'),
    "nav_add_to_cart" => __("Add to cart", 'us-barcode-scanner'),
    "nav_open_cart" => __("Open cart", 'us-barcode-scanner'),

    "tv_found" => __("Found", 'us-barcode-scanner'),
    "tv_not_found" => __("Not found", 'us-barcode-scanner'),
    "tv_searching" => __("Searching...", 'us-barcode-scanner'),
    "tv_qty_increasing" => __("Quantity increasing...", 'us-barcode-scanner'),
    "tv_qty_decreasing" => __("Quantity decreasing...", 'us-barcode-scanner'),
    "tv_qty_increased" => __("Quantity increased", 'us-barcode-scanner'),
    "tv_qty_decreased" => __("Quantity decreased", 'us-barcode-scanner'),
    "tv_found_items" => __("items", 'us-barcode-scanner'),

    "title_system_information" => __("System information", 'us-barcode-scanner'),
    "btn_send_report" => __("Send report", 'us-barcode-scanner'),
    "info_send_report" => __("Press button to send system info to tech support\n(for resolving issues)", 'us-barcode-scanner'),

    "title_settings" => __("Settings", 'us-barcode-scanner'),
    "ch_camera_sound" => __("Sound effects", 'us-barcode-scanner'),
    "ch_enable_camera" => __("Enable camera", 'us-barcode-scanner'),
    "ch_always_list_mode" => __("Always List mode", 'us-barcode-scanner'),
    "ch_allow_screen_rotation" => __("Allow screen rotation", 'us-barcode-scanner'),
    "ch_auto_screen_lock" => __("Auto screen lock", 'us-barcode-scanner'),
    "title_hand_gun" => __("Hand-gun scanner device:", 'us-barcode-scanner'),
    "handgun_scanner_legacy" => __("Legacy mode", 'us-barcode-scanner'),
    "handgun_scanner_input" => __("Input based mode", 'us-barcode-scanner'),
    "ch_enable_camera_confirm_desc" => __("You won't be able to scan the barcodes, do you really want to disable camera?\n\nThis option is useful only when you use the hand-gun barcode scanner connected to your phone by Bluetooth or cable.", 'us-barcode-scanner'),
    "btn_yes" => __("Yes", 'us-barcode-scanner'),
    "btn_no" => __("No", 'us-barcode-scanner'),

    "nav_back" => __("Back", 'us-barcode-scanner'),

    "tv_sku" => __("SKU", 'us-barcode-scanner'),
    "tv_id" => __("ID", 'us-barcode-scanner'),
    "tv_quantity" => __("Quantity", 'us-barcode-scanner'),
    "tv_regular_price" => __("Regular price", 'us-barcode-scanner'),
    "tv_sale_price" => __("Sale price", 'us-barcode-scanner'),
    "tv_cant_qty_increased" => __("Can't increase, stock is disabled.", 'us-barcode-scanner'),
    "tv_cant_qty_decreased" => __("Can't decrease, stock is disabled.", 'us-barcode-scanner'),
);
